name: Deploy connector, release cli on github
on:
  push:
    branches:
      - main
    tags:
      - "v*"

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ env.GHCR_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:build-cache
          cache-to: type=registry,ref=${{ env.GHCR_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:build-cache

  build-cli-binaries:
    name: build the CLI binaries
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-musl
            goos: linux
            goarch: amd64
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-musl
            goos: linux
            goarch: arm64
          - runner: macos-latest
            target: x86_64-apple-darwin
            goos: darwin
            goarch: amd64
          - runner: macos-latest
            target: aarch64-apple-darwin
            goos: darwin
            goarch: arm64
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            goos: windows
            goarch: amd64
            extension: .exe
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go environment
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: ./go.mod

      - name: Build binary
        run: |
          mkdir -p release
          echo "Building binary file for target: ${{ matrix.goos }}${{ matrix.goarch }}"
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -o ./release/ndc-elasticsearch-cli-${{ matrix.target }}${{ matrix.extension }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ndc-elasticsearch-cli-${{ matrix.target }}${{ matrix.extension }}
          path: release/
          if-no-files-found: error

  release:
    name: release to GitHub
    permissions:
      contents: write
    needs:
      - build-and-push-image
      - build-cli-binaries
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: release/artifacts
          merge-multiple: true

      - name: generate CLI manifest
        run: |
          set -evo pipefail
          ROOT="$(pwd)"

          export CLI_VERSION="$GITHUB_REF_NAME"

          export LINUX_AMD64_SHA256=$(sha256sum ${ROOT}/release/artifacts/ndc-elasticsearch-cli-x86_64-unknown-linux-musl     | cut -f1 -d' ')
          export MACOS_AMD64_SHA256=$(sha256sum ${ROOT}/release/artifacts/ndc-elasticsearch-cli-x86_64-apple-darwin           | cut -f1 -d' ')
          export WINDOWS_AMD64_SHA256=$(sha256sum ${ROOT}/release/artifacts/ndc-elasticsearch-cli-x86_64-pc-windows-msvc.exe  | cut -f1 -d' ')
          export LINUX_ARM64_SHA256=$(sha256sum ${ROOT}/release/artifacts/ndc-elasticsearch-cli-aarch64-unknown-linux-musl    | cut -f1 -d' ')
          export MACOS_ARM64_SHA256=$(sha256sum ${ROOT}/release/artifacts/ndc-elasticsearch-cli-aarch64-apple-darwin          | cut -f1 -d' ')

          mkdir -p "${ROOT}/release/"
          cat "${ROOT}/ci/templates/manifest.yaml" | envsubst > "${ROOT}/release/manifest.yaml"

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: manifest.yaml
          path: release/manifest.yaml
          if-no-files-found: error

      - name: Build connector definition
        run: |
          set -evo pipefail
          ROOT="$(pwd)"

          export DOCKER_IMAGE="ghcr.io/hasura/ndc-elasticsearch:$GITHUB_REF_NAME"
          export CLI_VERSION=$GITHUB_REF_NAME

          mkdir -p "${ROOT}/release/connector-definition/.hasura-connector/"
          cat "${ROOT}/ci/templates/connector-metadata.yaml" | envsubst '$DOCKER_IMAGE,$CLI_VERSION' > "${ROOT}/release/connector-definition/.hasura-connector/connector-metadata.yaml"
          tar -czvf "${ROOT}/release/artifacts/connector-definition.tgz" --directory "${ROOT}/release/connector-definition/" .

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: connector-definition.tgz
          path: ./release/artifacts/connector-definition.tgz
          compression-level: 0 # Already compressed

      - name: Get version from tag
        id: get-version
        run: |
          echo "tagged_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - uses: mindsers/changelog-reader-action@97a0b06549019bb99a571f1664272db18031acff # v2
        id: changelog-reader
        with:
          version: ${{ steps.get-version.outputs.tagged_version }}
          path: ./CHANGELOG.md

      - name: create a draft release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          draft: true
          tag: v${{ steps.get-version.outputs.tagged_version }}
          body: ${{ steps.changelog-reader.outputs.changes }}
          artifacts: release/artifacts/*
